baseURL = "https://kinfonia.github.io/"
title = "Tabula rasa"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  showReadingTime = true
  math = true
  enableInlineShortcodes = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "math"
  name = "Math"
  url = "/math/"
  weight = 20

[params.homeInfoParams]
  Title = "Tabula rasa"
  Content = "kinfonia's blog. @kinfonia. maths, music, other posts"

